### PR TITLE
Change HACS action

### PR DESCRIPTION
**Pull request by oncleben31**
To fix a warning with HACS GitHub Action.

### CODE REVIEW

**Review by ludeeus — CHANGES_REQUESTED** [review]
Move this to <https://github.com/hacs/action> instead

**Comment by oncleben31** [comment]
I don't understand you comment. The repository `https://github.com/hacs/action` is already using `main`. So currently in blueprint the branch master is used and you have a warning in CI ([check this message](https://github.com/custom-components/blueprint/runs/1400046770#step:5:11))

So if we want to remove the warning message we should modify blueprint to use the main branch for this action. It's what I'm doing in this PR.

**Comment by ludeeus** [comment]
instead of `hacs/integration/action@main` which will be removed, it's better to use `hacs/action@main`

**Comment by oncleben31** [comment]
Thank you for taking time. Now I understand your first comment.

**Comment by oncleben31** [comment]
Done

**Review by ludeeus — APPROVED** [review]

**Pull request merged**
